version: '3.8'

services:
  # Base de données SQL Server
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stocktrader-database
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: StockTrader2024!
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - stocktrader_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P StockTrader2024! -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # API Backend (image depuis GitHub Registry)
  api:
    image: ghcr.io/laHonda27/stocktrader/stocktrader-api:latest
    container_name: stocktrader-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5172:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Frontend React (image depuis GitHub Registry)
  frontend:
    image: ghcr.io/laHonda27/stocktrader/stocktrader-frontend:latest
    container_name: stocktrader-frontend
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  stocktrader_data:

networks:
  default:
    name: stocktrader-network